{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "argocd-ex.serviceAccountName" . }}
  labels:
{{ include "argocd-ex.labels" . | indent 4 }}
{{- end -}}
